### ISSUE TITLE
Replicating functionality?

### ISSUE THREAD

**Issue by pcav** [siddjain/wkt-plugin#1]
It seems to me that this plugin replicates some functions already in core, or in existing plugins: could you please check, and discuss about this on the qgis-dev mailing list?
Sorry to bother, but I' trying hard to reduce duplication, and confusion for the users.

**Comment by siddjain** [comment]
I couldn't find an existing plugin to do this. How did you find this repo btw? I know its public but wasn't expecting someone to bring an issue :)

**Comment by pcav** [comment]
From http://plugins.qgis.org/plugins/WKTBulkLoader/

**Comment by siddjain** [comment]
I will close this issue as resolved
