### ISSUE TITLE
To do a unique plugin Export and Load Wkt

### ISSUE THREAD

**Issue by geodrinx** [siddjain/wkt-plugin#2]
Hello Siddjain,

I am author of  WktExport  plugin  (and also of GEarthView and others :)

https://plugins.qgis.org/plugins/author/geodrinx/

Good morning  !     Happy to meet you.
I have seen you made a fantastic (I tell it without joking) plugin that loads all .wkt files in the same input folder.   Well, I writed a plugin that does the complement, that is saves a single wkt in a new folder named  WktExport/ 

Someone tells what we have done has no utility, but we do not care  :)   and..  if we programmed it, clearly for some reason we created our plugins.   So, we do not care what they think about.

Instead, sure we could join our efforts, and produce an unique "unuseful" plugin, that saves and loads .wkt  files.   And, over all, we can also write together a nice documentation that explain to all our philosophy about  .wkt  files   and what they offers in  quality control of geometry and its correction using the clear WKT  text definition.

What do you think about ?

I remain in wait of your contact

A presto

Roberto

**Comment by siddjain** [comment]
Hi Roberto, I'd rather discuss this privately. Could you provide me with your email address or alternatively are you able to send me a private email?

**Comment by geodrinx** [comment]
Hello Siddjain,

you can find my eMail address in info of my GEarthView plugin. 

A presto

Roberto

Inviato da iPhone
